### PR TITLE
Realtime Django Bugfix

### PR DESCRIPTION
**Pull request by lucernae**
Various bug fix effort for Realtime Django

### CODE REVIEW

**Comment by lucernae** [comment]
Change upload hazard file text.
issue inasafe/inasafe-realtime#27.
screen shot 2017-02-07 at 05 33 52

**Comment by lucernae** [comment]
Regarding issue:
- inasafe/inasafe-realtime#42
- inasafe/inasafe-realtime#48
- inasafe/inasafe-realtime#11

Changes:
- highlight latest flood by default (inasafe/inasafe-realtime#42)
- add stroke color in landing page map for affected RW (inasafe/inasafe-realtime#48)
- change time description according (inasafe/inasafe-realtime#11)
- add population affected and flooded RW (inasafe/inasafe-realtime#11)
- change flood models to cache population affected and flooded RW (inasafe/inasafe-realtime#11)
- only shows 6 hour interval flood and ignore the rest (inasafe/inasafe-realtime#11)

screen shot 2017-02-07 at 05 36 16

**Comment by gubuntu** [comment]
@lucernae we don't merge until travis passes, correct?

In ash upload form change 'meter' to 'meters' or 'metres' (Does InaSAFE have a policy on British vs American spelling?)

**Comment by Gustry** [comment]
>In ash upload form change 'meter' to 'meters' or 'metres' (Does InaSAFE have a policy on British vs American spelling?)

It's `metres`.

**Comment by timlinux** [comment]
Yes British english please

**Comment by lucernae** [comment]
It's not done yet until @ivanbusthomi gives all the checkmark 😄

**Comment by lucernae** [comment]
@timlinux How do you configure coveralls?

**Comment by ivanbusthomi** [comment]
I think the changes are great, especially the new filter function. Here are my comments on this:
* in staging, I check the filter is not working. Is it still bugged?
* Is it possible to change the layout of the filter a little bit? maybe something like this. Mas @samnawi, what do you think?
image

**Comment by lucernae** [comment]
> in staging, I check the filter is not working. Is it still bugged?

@ivanbusthomi try hard refresh (shift + refresh or ctrl + refresh) so the new javascript is loaded.

> Is it possible to change the layout of the filter a little bit? maybe something like this. Mas @samnawi, what do you think?

I think that's neat. It's possible to arrange it like that if that's ok with everyone.

**Comment by samnawi** [comment]
HI @ivanbusthomi That's great

**Comment by lucernae** [comment]
Additional changes:

based on issue inasafe/inasafe-realtime#35

Earthquake:
- [ ] Add download button for MMI Output zip (hide if it doesn't exists)
- [ ] Auto zoom to first earthquake in the table

screen shot 2017-02-10 at 08 03 02
screen shot 2017-02-10 at 08 03 17

Flood:
- Add support for PetaBencana
- [ ] Add download button for Hazard File and Impact Layers (hide if it doesn't exists)
- [ ] Change download button icon to follow Earthquake pattern

screen shot 2017-02-10 at 08 04 21

Ash:
- [ ] Add download button for Impact Files zip (hide if it doesn't exists)
- [ ] Change download button icon to follow Earthquake pattern
- [ ] Auto zoom to first ash event in the table

screen shot 2017-02-10 at 08 05 29
screen shot 2017-02-10 at 08 05 36

**Comment by ivanbusthomi** [comment]
This is great Mas @lucernae , 
:+1:

**Comment by gubuntu** [comment]
almost there.
- when is Ash going to be deployed on staging?
- I get the same issue as https://github.com/inasafe/inasafe-django/pull/152#issuecomment-278840513 (Firefox)
- I think there is a bit much white space around the filters.

**Comment by lucernae** [comment]
@gubuntu Ash is deployed on staging. You have to login first for Ash. I will give the credentials later.

For the cropped part, I think that's because of the overflow. I'll see what I can do. But you should be able to horizontal scroll it to see the text?

**Comment by gubuntu** [comment]
yes I can horizontal scroll. white space to the right of the text in that block could also be reduced.

**Comment by ivanbusthomi** [comment]
Hi @gubuntu , and @lucernae 
So here's my suggestion on reducing whitespace in the Filters area. 
image

* I think we can also make the warning text `Value must be greater than or equal to 0.` smaller, or just responsively resize the `Filters` box if the warning appear.
* It would be great if the margin of `Filters` and `Flood` section are same.
* The accept and clear button should be aligned with the other input maybe
* Maybe also add `Clear` and `Accept` text on top of the button?

**Comment by lucernae** [comment]
Some left issues were moved to #153 and I will merge this right away.

**Pull request merged**
